package Entity;
// Generated 10/10/2019 08:13:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Presentacion generated by hbm2java
 */
public class Presentacion  implements java.io.Serializable {


     private int idPresentacion;
     private String descripcion;
     private Set<Producto> productos = new HashSet<Producto>(0);
     private Set<Producto> productos_1 = new HashSet<Producto>(0);

    public Presentacion() {
    }

	
    public Presentacion(int idPresentacion, String descripcion) {
        this.idPresentacion = idPresentacion;
        this.descripcion = descripcion;
    }
    public Presentacion(int idPresentacion, String descripcion, Set<Producto> productos, Set<Producto> productos_1) {
       this.idPresentacion = idPresentacion;
       this.descripcion = descripcion;
       this.productos = productos;
       this.productos_1 = productos_1;
    }
   
    public int getIdPresentacion() {
        return this.idPresentacion;
    }
    
    public void setIdPresentacion(int idPresentacion) {
        this.idPresentacion = idPresentacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }
    public Set<Producto> getProductos_1() {
        return this.productos_1;
    }
    
    public void setProductos_1(Set<Producto> productos_1) {
        this.productos_1 = productos_1;
    }




}


